---
firewall_open_ports:
  - { port: 80, prot: tcp }
  - { port: 443, prot: tcp }
  - { port: 22, prot: tcp }

stack_name: bps

authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCftXa/vwLo8HvDatDiwZUbvxPJGn+pzHjI8GciL4IeeqGwuQOKlswNIGyi8vpR3VgF4ZS1qC9fjkzMh3XddxttqChaZt0DSe0swBPB2S+0GNpUKDRdVqrZDR24g/FOhU6mEy18k0k7bmZyVzbxN31cIGiZEpDw3cdUizapwHhPzvvvtI1fOTePwyCW8CfKAAKxtjzfz8qDtuYuFXDuixmfpL9tyIODwExw6cZXTRy3VZkrn1eqzWzSoFpEXID6w+7yEyVX5lyESMTdjQtD8yR7d6WRNdj88b+wXt+4njBfaoq57WRRQqp5ShP+nqcZv3tuVPE4VTiLUyrCgV4ySQD7byXUaqdShYa3BvZI0ZwWQqnk6Mvx4Jrb8PIPD1GFRj1aNouiwp9WDbPMQtJVfldac/wz+44cuWBPuKmijS3TOjKnOLa9YObMghHyzb0GHoBgbAtAJzlWnBUQylTnFGkTL6cA1YfxDKqtuvIDezzbr8wD3/9XZ5R8EAGCXbvArRswRNB2p37I+4xYzv06+IBFqQJKIhDGBFjoyVL0ubVdK5Bf5L0qxDPf6Kx8u8u2A2tBysfdxLd9Bgc/yhk5h3HbkBbEQabGgueX2nW9brJNw/yVtmJ4znWyLobI0izcl1z8jRPhs/q7xMiCopsjQHbCLxwYlg9WINte4p+l3HYC2Q== terraform"
