- hosts: app
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - common
    - firewall
    - docker

  tasks:
    - name: Install pip dependencies
      pip:
        name:
          - jsondiff
        state: latest

    - name: Create docker stack file
      template:
        src: "templates/stack.yml.j2"
        dest: "/opt/stack.yml"
        owner: root
        group: root
        mode: "0664"

    - name: Create nginx docker dir
      file:
        path: "/opt/nginx"
        state: directory
        mode: "0664"

    - name: Create nginx config file
      template:
        src: "templates/nginx.conf.j2"
        dest: "/opt/nginx/nginx.conf"
        owner: "root"
        group: "root"
        mode: "0664"

    - name: Create docker swarm
      community.docker.docker_swarm:
        advertise_addr: 10.114.0.2
        heartbeat_tick: 10
        state: present

    - name: Deploy docker stack
      community.docker.docker_stack:
        name: "{{ stack_name }}"
        state: present
        compose:
          - /opt/stack.yml

    - name: Copy certbot script
      template:
        src: "templates/certbot.sh.j2"
        dest: "/opt/certbot.sh"
        owner: "root"
        group: "root"
        mode: "0774"

    - name: Add cronjob for certbot
      cron:
        name: Run certbot
        job: /opt/certbot.sh
        day: 1
