- name: Install firewalld from package manager, if missing
  package:
    name: firewalld
    state: latest

- name: Start/Enable firewalld service, if not running
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Open ports, if not open
  ansible.posix.firewalld:
    port: "{{ item.port }}/{{ item.prot }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items: "{{ firewall_open_ports }}"
