- name: Install nginx from package manager
  package:
    name:
      - "{{ item.value }}"
    state: latest
  with_dict:
    - CentOS: "nginx"
    - Archlinx": "nginx-mainline"
  when: item.key == ansible_facts["distribution"]

- name: Create nginx user '{{ nginx_user }}', if missing
  user:
    name: "{{ nginx_user }}"
    state: present

- name: Create nginx.conf template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0664"
    validate: "nginx -t -c %s"
  notify: Restart nginx

- name: Enable nginx service, if not active
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
