- name: Install dependencies from package manager
  package:
    name:
      - docker
    state: latest
  when: ansible_facts["distribution"] == "Archlinux"

- name: Check if docker-ce in yum repo
  command: yum repolist
  register: yum_repolist
  when: ansible_facts["distribution"] == "CentOS"
  changed_when: false

- name: Add docker-ce yum repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts["distribution"] == "CentOS" and "docker-ce" not in yum_repolist.stdout

- name: Install dependencies for CentOS
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  when: ansible_facts["distribution"] == "CentOS"

- name: Install Docker PIP dependencies, if missing
  pip:
    name:
      - docker
    state: latest

- name: Start docker service, if not running
  service:
    name: docker
    state: started
    enabled: yes
